# Introduction

In this notebook, we will do a comprehensive analysis of the Android app market by comparing thousands of apps in the Google Play store.

In [76]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# About the Dataset of Google Play Store Apps & Reviews

**Data Source:** <br>
App and review data was scraped from the Google Play Store by Lavanya Gupta in 2018. Original files listed [here](
https://www.kaggle.com/lava18/google-play-store-apps).

# Import Statements

In [77]:
import pandas as pd

# Notebook Presentation

In [78]:
# Notebook Presentation #
# Show numeric output in decimal format e.g., 2.15
pd.options.display.float_format = '{:,.2f}'.format

# Read the Dataset

In [79]:
# Read the Dataset
df_apps = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/apps.csv')

# Data Cleaning

**Challenge**: How many rows and columns does `df_apps` have? What are the column names? Look at a random sample of 5 different rows with [.sample()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html).

In [80]:
df_apps.shape

(10841, 12)

In [81]:
df_apps.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size_MBs', 'Installs', 'Type',
       'Price', 'Content_Rating', 'Genres', 'Last_Updated', 'Android_Ver'],
      dtype='object')

In [82]:
# Provides better description of columns
df_apps.info(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  int64
 4   Size_MBs        10841 non-null  float64
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content_Rating  10841 non-null  object
 9   Genres          10841 non-null  object
 10  Last_Updated    10841 non-null  object
 11  Android_Ver     10839 non-null  object
dtypes: float64(2), int64(1), object(9)
memory usage: 1016.5+ KB

In [83]:
df_apps.sample(n=5)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Android_Ver
9712,Camera for Android,PHOTOGRAPHY,4.20,240475,9.50,"10,000,000",Free,0,Everyone,Photography,"November 22, 2017",4.0 and up
10298,Earn to Die 2,GAME,4.60,1327269,99.00,"50,000,000",Free,0,Teen,Racing,"April 12, 2017",2.3.3 and up
4838,YAY - TBH,SOCIAL,4.10,2520,12.00,"100,000",Free,0,Teen,Social,"November 17, 2017",4.3 and up
10351,Telegram,COMMUNICATION,4.40,3128509,3.50,"100,000,000",Free,0,Mature 17+,Communication,"July 27, 2018",Varies with device
955,EF Staff,PRODUCTIVITY,NaN,0,11.00,100,Free,0,Everyone,Productivity,"May 8, 2018",4.2 and up

### Drop Unused Columns

**Challenge**: Remove the columns called `Last_Updated` and `Android_Version` from the DataFrame. We will not use these columns.

In [84]:
df_apps.drop(['Last_Updated', 'Android_Ver'], axis=1, inplace=True)

In [85]:
df_apps.sample(n=5)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
303,FK Macva Sabac,SPORTS,NaN,3,26.00,10,Free,0,Everyone,Sports
10612,Cut the Rope FULL FREE,GAME,4.40,2123793,49.00,"100,000,000",Free,0,Everyone,Puzzle
10034,Frozen Free Fall,FAMILY,4.30,1574204,37.00,"50,000,000",Free,0,Everyone,Puzzle;Action & Adventure
4492,Pick Your Part Garage,AUTO_AND_VEHICLES,3.90,142,32.00,"50,000",Free,0,Everyone,Auto & Vehicles
3998,Bullshit! (Free),GAME,2.40,45,4.10,"10,000",Free,0,Teen,Card

### Find and Remove NaN values in Ratings

**Challenge**: How may rows have a NaN value (not-a-number) in the Ratings column? Create DataFrame called `df_apps_clean` that does not include these rows.

In [86]:
# Check for NaN across entire DF
df_apps.isna()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
0,False,False,True,False,False,False,False,False,False,False
1,False,False,True,False,False,False,False,False,False,False
2,False,False,True,False,False,False,False,False,False,False
3,False,False,True,False,False,False,True,False,False,False
4,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
10836,False,False,False,False,False,False,False,False,False,False
10837,False,False,False,False,False,False,False,False,False,False
10838,False,False,False,False,False,False,False,False,False,False
10839,False,False,False,False,False,False,False,False,False,False
10840,False,False,False,False,False,False,False,False,False,False

In [87]:
len(df_apps[df_apps.Rating.isna()])

1474

In [88]:
nan_rows = df_apps[df_apps.Rating.isna()]

In [89]:
print(nan_rows.shape)

(1474, 10)

In [90]:
nan_rows.head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
0,Ak Parti Yardım Toplama,SOCIAL,NaN,0,8.70,0,Paid,$13.99,Teen,Social
1,Ain Arabic Kids Alif Ba ta,FAMILY,NaN,0,33.00,0,Paid,$2.99,Everyone,Education
2,Popsicle Launcher for Android P 9.0 launcher,PERSONALIZATION,NaN,0,5.50,0,Paid,$1.49,Everyone,Personalization
3,Command & Conquer: Rivals,FAMILY,NaN,0,19.00,0,NaN,0,Everyone 10+,Strategy
4,CX Network,BUSINESS,NaN,0,10.00,0,Free,0,Everyone,Business

In [91]:
df_apps_clean = df_apps.dropna()

In [92]:
df_apps_clean.shape

(9367, 10)

### Find and Remove Duplicates

**Challenge**: Are there any duplicates in data? Check for duplicates using the [.duplicated()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.duplicated.html) function. How many entries can you find for the "Instagram" app? Use [.drop_duplicates()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop_duplicates.html) to remove any duplicates from `df_apps_clean`.

In [93]:
# Gather together duplicate rows
duplicated_rows = df_apps_clean[df_apps_clean.duplicated]

In [94]:
# check/review gathered rows
print(duplicated_rows.shape)

(476, 10)

In [95]:
# check/review gathered rows
duplicated_rows.head(10)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
946,420 BZ Budeze Delivery,MEDICAL,5.00,2,11.00,100,Free,0,Mature 17+,Medical
1133,MouseMingle,DATING,2.70,3,3.90,100,Free,0,Mature 17+,Dating
1196,"Cardiac diagnosis (heart rate, arrhythmia)",MEDICAL,4.40,8,6.50,100,Paid,$12.99,Everyone,Medical
1231,Sway Medical,MEDICAL,5.00,3,22.00,100,Free,0,Everyone,Medical
1247,Chat Kids - Chat Room For Kids,DATING,4.70,6,4.90,100,Free,0,Mature 17+,Dating
1379,CT Scan Cross Sectional Anatomy,MEDICAL,4.30,10,46.00,100,Free,0,Everyone,Medical
1616,JH Blood Pressure Monitor,MEDICAL,3.70,9,2.90,500,Free,0,Everyone,Medical
1642,Cardi B Live Stream Video Chat - Prank,DATING,4.40,28,3.40,500,Free,0,Everyone,Dating
1813,Diabetes & Diet Tracker,MEDICAL,4.60,395,19.00,"1,000",Paid,$9.99,Everyone,Medical
1821,Transenger – Ts Dating and Chat for Free,DATING,3.60,8,14.00,"1,000",Free,0,Mature 17+,Dating

In [96]:
# check/review gathered rows -> App = Instagram
df_apps_clean[df_apps_clean.App == 'Instagram']

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
10806,Instagram,SOCIAL,4.50,66577313,5.30,"1,000,000,000",Free,0,Teen,Social
10808,Instagram,SOCIAL,4.50,66577446,5.30,"1,000,000,000",Free,0,Teen,Social
10809,Instagram,SOCIAL,4.50,66577313,5.30,"1,000,000,000",Free,0,Teen,Social
10810,Instagram,SOCIAL,4.50,66509917,5.30,"1,000,000,000",Free,0,Teen,Social

In [97]:
# specify subset (column names) for comparison and dropping duplicates
df_apps_clean = df_apps_clean.drop_duplicates(subset=['App', 'Type', 'Price'])

In [98]:
df_apps_clean.shape

(8199, 10)

# Find Highest Rated Apps

**Challenge**: Identify which apps are the highest rated. What problem might you encounter if you rely exclusively on ratings alone to determine the quality of an app?

In [99]:
df_apps_clean.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size_MBs', 'Installs', 'Type',
       'Price', 'Content_Rating', 'Genres'],
      dtype='object')

In [100]:
# Identify which apps are the highest rated.
df_apps_clean.sort_values('Rating', ascending=False).head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
21,KBA-EZ Health Guide,MEDICAL,5.00,4,25.00,1,Free,0,Everyone,Medical
1751,Spine- The dating app,DATING,5.00,5,9.30,500,Free,0,Teen,Dating
1761,Selfie With Champion AJ Style,PHOTOGRAPHY,5.00,2,7.50,500,Free,0,Everyone,Photography
1763,Ag Valley Cooperative,BUSINESS,5.00,6,74.00,500,Free,0,Everyone,Business
1769,Yazdani Cd Center EllahAbad Official App,FAMILY,5.00,8,3.80,500,Free,0,Everyone,Entertainment

# Find 5 Largest Apps in terms of Size (MBs)

**Challenge**: What's the size in megabytes (MB) of the largest Android apps in the Google Play Store. Based on the data, do you think there could be limit in place or can developers make apps as large as they please?

In [101]:
# Identify the 5 largest Apps
df_apps_clean.sort_values('Size_MBs', ascending=False).head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
8719,Draft Simulator for FUT 18,SPORTS,4.60,162933,100.00,"5,000,000",Free,0,Everyone,Sports
8718,Mini Golf King - Multiplayer Game,GAME,4.50,531458,100.00,"5,000,000",Free,0,Everyone,Sports
10295,SimCity BuildIt,FAMILY,4.50,4218587,100.00,"50,000,000",Free,0,Everyone 10+,Simulation
9945,Ultimate Tennis,SPORTS,4.30,183004,100.00,"10,000,000",Free,0,Everyone,Sports
9944,Gangster Town: Vice District,FAMILY,4.30,65146,100.00,"10,000,000",Free,0,Mature 17+,Simulation

# Find the 5 App with Most Reviews

**Challenge**: Which apps have the highest number of reviews? Are there any paid apps among the top 50?

In [102]:
# Identify the 5 most reviewed Apps
df_apps_clean.sort_values('Reviews', ascending=False).head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
10805,Facebook,SOCIAL,4.10,78158306,5.30,"1,000,000,000",Free,0,Teen,Social
10785,WhatsApp Messenger,COMMUNICATION,4.40,69119316,3.50,"1,000,000,000",Free,0,Everyone,Communication
10806,Instagram,SOCIAL,4.50,66577313,5.30,"1,000,000,000",Free,0,Teen,Social
10784,Messenger – Text and Video Chat for Free,COMMUNICATION,4.00,56642847,3.50,"1,000,000,000",Free,0,Everyone,Communication
10650,Clash of Clans,GAME,4.60,44891723,98.00,"100,000,000",Free,0,Everyone 10+,Strategy

In [103]:
# Identify the 5 most reviewed Apps
df_apps_clean.nlargest(5, 'Reviews')

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
10805,Facebook,SOCIAL,4.10,78158306,5.30,"1,000,000,000",Free,0,Teen,Social
10785,WhatsApp Messenger,COMMUNICATION,4.40,69119316,3.50,"1,000,000,000",Free,0,Everyone,Communication
10806,Instagram,SOCIAL,4.50,66577313,5.30,"1,000,000,000",Free,0,Teen,Social
10784,Messenger – Text and Video Chat for Free,COMMUNICATION,4.00,56642847,3.50,"1,000,000,000",Free,0,Everyone,Communication
10650,Clash of Clans,GAME,4.60,44891723,98.00,"100,000,000",Free,0,Everyone 10+,Strategy

# Plotly Pie and Donut Charts - Visualise Categorical Data: Content Ratings

In [104]:
# Import Statements
import pandas as pd
# Import ploltly for charts
import plotly.express as px

In [105]:
# look at the distribution of the content ratings
ratings = df_apps_clean.Content_Rating.value_counts()
ratings

Content_Rating
Everyone           6621
Teen                912
Mature 17+          357
Everyone 10+        305
Adults only 18+       3
Unrated               1
Name: count, dtype: int64

In [106]:
# To create a pie chart
fig = px.pie(labels=ratings.index,
values=ratings.values,
title="Content Rating",
names=ratings.index,
)

fig.update_traces(textposition='outside', textinfo='percent+label')

fig.show()

In [107]:
# To create a donut chart (simply add hole)
fig = px.pie(labels=ratings.index,
values=ratings.values,
title="Content Rating",
names=ratings.index,
             hole=0.6
)
#  update the traces to change how the text is displayed.
fig.update_traces(textposition='outside', textinfo='percent+label')

fig.show()

# Numeric Type Conversion: Examine the Number of Installs

**Challenge**: How many apps had over 1 billion (that's right - BILLION) installations? How many apps just had a single install?

Check the datatype of the Installs column.

Count the number of apps at each level of installations.

Convert the number of installations (the Installs column) to a numeric data type. Hint: this is a 2-step process. You'll have make sure you remove non-numeric characters first.

In [108]:
df_apps_clean.tail()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
10824,Google Drive,PRODUCTIVITY,4.40,2731171,4.00,"1,000,000,000",Free,0,Everyone,Productivity
10828,YouTube,VIDEO_PLAYERS,4.30,25655305,4.65,"1,000,000,000",Free,0,Teen,Video Players & Editors
10829,Google Play Movies & TV,VIDEO_PLAYERS,3.70,906384,4.65,"1,000,000,000",Free,0,Teen,Video Players & Editors
10831,Google News,NEWS_AND_MAGAZINES,3.90,877635,13.00,"1,000,000,000",Free,0,Teen,News & Magazines
10835,Subway Surfers,GAME,4.50,27722264,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade

In [109]:
# Check DataType of Installs column   (DataType = 'Object', meaning non-numerical data type)
df_apps_clean.Installs.describe()

count          8199
unique           19
top       1,000,000
freq           1417
Name: Installs, dtype: object

In [110]:
# Check DataTypes of all columns
df_apps_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8199 entries, 21 to 10835
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             8199 non-null   object
 1   Category        8199 non-null   object
 2   Rating          8199 non-null   float64
 3   Reviews         8199 non-null   int64
 4   Size_MBs        8199 non-null   float64
 5   Installs        8199 non-null   object
 6   Type            8199 non-null   object
 7   Price           8199 non-null   object
 8   Content_Rating  8199 non-null   object
 9   Genres          8199 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 704.6+ KB

In [111]:
# Remove commas (pre-cursor to change to numeric)
df_apps_clean.Installs = df_apps_clean.Installs.astype(str).str.replace(',', "")

In [112]:
# Change column 'Installs' dtype to numeric
df_apps_clean.Installs = pd.to_numeric(df_apps_clean.Installs)

In [113]:
# Check DataTypes of all columns (Note int64 datatype for 'Installs)
df_apps_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8199 entries, 21 to 10835
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             8199 non-null   object
 1   Category        8199 non-null   object
 2   Rating          8199 non-null   float64
 3   Reviews         8199 non-null   int64
 4   Size_MBs        8199 non-null   float64
 5   Installs        8199 non-null   int64
 6   Type            8199 non-null   object
 7   Price           8199 non-null   object
 8   Content_Rating  8199 non-null   object
 9   Genres          8199 non-null   object
dtypes: float64(2), int64(2), object(6)
memory usage: 704.6+ KB

In [114]:
# Count number of 'Installs' per number of Apps
df_apps_clean[['App', 'Installs']].groupby('Installs').count()

             App
Installs
1              3
5              9
10            69
50            56
100          303
500          199
1000         698
5000         425
10000        988
50000        457
100000      1096
500000       504
1000000     1417
5000000      607
10000000     933
50000000     202
100000000    189
500000000     24
1000000000    20

# Find the Most Expensive Apps, Filter out the Junk, and Calculate a (ballpark) Sales Revenue Estimate

Let's examine the Price column more closely.

**Challenge**: Convert the price column to numeric data. Then investigate the top 20 most expensive apps in the dataset.

Remove all apps that cost more than $250 from the `df_apps_clean` DataFrame.

Add a column called 'Revenue_Estimate' to the DataFrame. This column should hold the price of the app times the number of installs. What are the top 10 highest grossing paid apps according to this estimate? Out of the top 10 highest grossing paid apps, how many are games?

In [115]:
# Check DataType of all columns
df_apps_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8199 entries, 21 to 10835
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             8199 non-null   object
 1   Category        8199 non-null   object
 2   Rating          8199 non-null   float64
 3   Reviews         8199 non-null   int64
 4   Size_MBs        8199 non-null   float64
 5   Installs        8199 non-null   int64
 6   Type            8199 non-null   object
 7   Price           8199 non-null   object
 8   Content_Rating  8199 non-null   object
 9   Genres          8199 non-null   object
dtypes: float64(2), int64(2), object(6)
memory usage: 704.6+ KB

In [116]:
# Check Price column content
df_apps_clean.Price.unique()

array(['0', '$1.49', '$0.99', '$14.99', '$2.49', '$3.04', '$3.49',
       '$2.99', '$4.99', '$29.99', '$19.99', '$1.99', '$1.76', '$8.99',
       '$1.75', '$12.99', '$7.99', '$3.99', '$3.88', '$4.59', '$9.99',
       '$14.00', '$4.49', '$6.99', '$399.99', '$5.99', '$39.99', '$3.02',
       '$6.49', '$17.99', '$2.00', '$15.99', '$10.99', '$1.61', '$4.29',
       '$15.46', '$7.49', '$5.49', '$1.70', '$379.99', '$79.99', '$2.56',
       '$8.49', '$1.50', '$4.84', '$19.40', '$33.99', '$3.08', '$16.99',
       '$37.99', '$10.00', '$1.29', '$4.60', '$1.00', '$24.99', '$2.50',
       '$3.90', '$2.95', '$1.97', '$3.28', '$299.99', '$389.99', '$1.20',
       '$400.00', '$2.59', '$18.99', '$1.59', '$11.99', '$4.77', '$9.00',
       '$3.95', '$13.99', '$2.90'], dtype=object)

In [117]:
# Remove Dollar Signs (pre-cursor to change to numeric)
df_apps_clean.Price = df_apps_clean.Price.astype(str).str.replace('$', "")

In [118]:
# Change column 'Price' dtype to numeric
df_apps_clean.Price = pd.to_numeric(df_apps_clean.Price)

In [119]:
# Check DataType of all columns (Price column now numeric)
df_apps_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8199 entries, 21 to 10835
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             8199 non-null   object
 1   Category        8199 non-null   object
 2   Rating          8199 non-null   float64
 3   Reviews         8199 non-null   int64
 4   Size_MBs        8199 non-null   float64
 5   Installs        8199 non-null   int64
 6   Type            8199 non-null   object
 7   Price           8199 non-null   float64
 8   Content_Rating  8199 non-null   object
 9   Genres          8199 non-null   object
dtypes: float64(3), int64(2), object(5)
memory usage: 704.6+ KB

In [120]:
#  investigate the top 20 most expensive apps in the dataset.
df_apps_clean.nlargest(20, 'Price')

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
3946,I'm Rich - Trump Edition,LIFESTYLE,3.60,275,7.30,10000,Paid,400.00,Everyone,Lifestyle
1331,most expensive app (H),FAMILY,4.30,6,1.50,100,Paid,399.99,Everyone,Entertainment
1946,I am rich (Most expensive app),FINANCE,4.10,129,2.70,1000,Paid,399.99,Teen,Finance
2394,I am Rich!,FINANCE,3.80,93,22.00,1000,Paid,399.99,Everyone,Finance
2461,I AM RICH PRO PLUS,FINANCE,4.00,36,41.00,1000,Paid,399.99,Everyone,Finance
2775,I Am Rich Pro,FAMILY,4.40,201,2.70,5000,Paid,399.99,Everyone,Entertainment
3114,I am Rich,FINANCE,4.30,180,3.80,5000,Paid,399.99,Everyone,Finance
3145,I am rich(premium),FINANCE,3.50,472,0.94,5000,Paid,399.99,Everyone,Finance
3221,I am Rich Plus,FAMILY,4.00,856,8.70,10000,Paid,399.99,Everyone,Entertainment
3554,💎 I'm rich,LIFESTYLE,3.80,718,26.00,10000,Paid,399.99,Everyone,Lifestyle
4606,I Am Rich Premium,FINANCE,4.10,1867,4.70,50000,Paid,399.99,Everyone,Finance
5765,I am rich,LIFESTYLE,3.80,3547,1.80,100000,Paid,399.99,Everyone,Lifestyle
3897,I Am Rich,FAMILY,3.60,217,4.90,10000,Paid,389.99,Everyone,Entertainment
2193,I am extremely Rich,LIFESTYLE,2.90,41,2.90,1000,Paid,379.99,Everyone,Lifestyle
3856,I am rich VIP,LIFESTYLE,3.80,411,2.60,10000,Paid,299.99,Everyone,Lifestyle
2281,Vargo Anesthesia Mega App,MEDICAL,4.60,92,32.00,1000,Paid,79.99,Everyone,Medical
1407,LTC AS Legal,MEDICAL,4.00,6,1.30,100,Paid,39.99,Everyone,Medical
2629,I am Rich Person,LIFESTYLE,4.20,134,1.80,1000,Paid,37.99,Everyone,Lifestyle
2481,A Manual of Acupuncture,MEDICAL,3.50,214,68.00,1000,Paid,33.99,Everyone,Medical
504,AP Art History Flashcards,FAMILY,5.00,1,96.00,10,Paid,29.99,Mature 17+,Education

### The most expensive apps sub $250

### Highest Grossing Paid Apps (ballpark estimate)

In [121]:
# Strip out Apps with prices greater than 250
df_apps_clean = df_apps_clean[df_apps_clean['Price'] < 250]

In [122]:
# List Top 5 Apps by Price
df_apps_clean.sort_values('Price', ascending=False).head(5)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
2281,Vargo Anesthesia Mega App,MEDICAL,4.60,92,32.00,1000,Paid,79.99,Everyone,Medical
1407,LTC AS Legal,MEDICAL,4.00,6,1.30,100,Paid,39.99,Everyone,Medical
2629,I am Rich Person,LIFESTYLE,4.20,134,1.80,1000,Paid,37.99,Everyone,Lifestyle
2481,A Manual of Acupuncture,MEDICAL,3.50,214,68.00,1000,Paid,33.99,Everyone,Medical
504,AP Art History Flashcards,FAMILY,5.00,1,96.00,10,Paid,29.99,Mature 17+,Education

In [123]:
# Calculate Revenue Estimate Column using .mul()
df_apps_clean['Revenue Estimate'] = df_apps_clean.Installs.mul(df_apps_clean.Price)

In [124]:
# List Top 10 Apps by Revenue Estimate
df_apps_clean.sort_values('Revenue Estimate', ascending=False)[:10]

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Revenue Estimate
9220,Minecraft,FAMILY,4.50,2376564,19.00,10000000,Paid,6.99,Everyone 10+,Arcade;Action & Adventure,"69,900,000.00"
8825,Hitman Sniper,GAME,4.60,408292,29.00,10000000,Paid,0.99,Mature 17+,Action,"9,900,000.00"
7151,Grand Theft Auto: San Andreas,GAME,4.40,348962,26.00,1000000,Paid,6.99,Mature 17+,Action,"6,990,000.00"
7477,Facetune - For Free,PHOTOGRAPHY,4.40,49553,48.00,1000000,Paid,5.99,Everyone,Photography,"5,990,000.00"
7977,Sleep as Android Unlock,LIFESTYLE,4.50,23966,0.85,1000000,Paid,5.99,Everyone,Lifestyle,"5,990,000.00"
6594,DraStic DS Emulator,GAME,4.60,87766,12.00,1000000,Paid,4.99,Everyone,Action,"4,990,000.00"
6082,Weather Live,WEATHER,4.50,76593,4.75,500000,Paid,5.99,Everyone,Weather,"2,995,000.00"
6746,Card Wars - Adventure Time,FAMILY,4.30,129603,23.00,1000000,Paid,2.99,Everyone 10+,Card;Action & Adventure,"2,990,000.00"
7633,Five Nights at Freddy's,GAME,4.60,100805,50.00,1000000,Paid,2.99,Teen,Action,"2,990,000.00"
7954,Bloons TD 5,FAMILY,4.60,190086,94.00,1000000,Paid,2.99,Everyone,Strategy,"2,990,000.00"

# Plotly Bar Charts & Scatter Plots: Analysing App Categories

In [125]:
# Find the number of different categories
df_apps_clean.Category.nunique()

33

In [126]:
# Calculate the number of apps per category
top10_category = df_apps_clean.Category.value_counts()[:10]
top10_category

Category
FAMILY             1606
GAME                910
TOOLS               719
PRODUCTIVITY        301
PERSONALIZATION     298
LIFESTYLE           297
FINANCE             296
MEDICAL             292
PHOTOGRAPHY         263
BUSINESS            262
Name: count, dtype: int64

### Vertical Bar Chart - Highest Competition (Number of Apps)

In [127]:
bar = px.bar(x=top10_category.index, y = top10_category.values)
bar.show()

Based on the number of apps, the Family and Game categories are the most competitive. Releasing yet another app into these categories will make it hard to get noticed.

How often apps are downloaded per category?
This will give us an idea of how popular a category is.

First, we have to group all our apps by category and sum the number of installations:

### Horizontal Bar Chart - Most Popular Categories (Highest Downloads)

<p>How often apps are downloaded per category?<br>
This will give us an idea of how popular a category is.<br>
Group all  apps by category and sum the number of installations.</p>

In [128]:
# Group all apps by category and sum the number of installations
category_installs = df_apps_clean.groupby('Category').agg({'Installs':pd.Series.sum})

In [129]:
# Sort by number of Installs ascending
category_installs.sort_values('Installs', ascending=False, inplace=True)

In [130]:
# List the Top 5 Categories
category_installs.head()

                  Installs
Category
GAME           13858762717
COMMUNICATION  11039241530
TOOLS           8099724500
PRODUCTIVITY    5788070180
SOCIAL          5487841475

In [131]:
# Specify chart content
h_bar = px.bar(x = category_installs.Installs, y = category_installs.index, orientation ='h', title='Category Popularity' )

# Add a custom title and axis labels
h_bar.update_layout(xaxis_title='Number of Installs', yaxis_title='Category')

# Display Chart
h_bar.show()

<p>We see that Games and Tools are actually the most popular categories.<br> If we plot the popularity of a category next to the number of apps in that category we can get an idea of how concentrated a category is.<br><br> Do a few apps have most of the downloads or are the downloads spread out over many apps?</p>

### Category Concentration - Downloads vs. Competition

**Challenge**:
* First, create a DataFrame that has the number of apps in one column and the number of installs in another:

<img src=https://imgur.com/uQRSlXi.png width="350">

* Then use the [plotly express examples from the documentation](https://plotly.com/python/line-and-scatter/) alongside the [.scatter() API reference](https://plotly.com/python-api-reference/generated/plotly.express.scatter.html)to create scatter plot that looks like this.

<img src=https://imgur.com/cHsqh6a.png>

*Hint*: Use the size, hover_name and color parameters in .scatter(). To scale the yaxis, call .update_layout() and specify that the yaxis should be on a log-scale like so: yaxis=dict(type='log')

In [132]:
# Count the number of Apps by category
cat_number = df_apps_clean.groupby('Category').agg({'App':pd.Series.count})
cat_number.head()

                     App
Category
ART_AND_DESIGN        61
AUTO_AND_VEHICLES     73
BEAUTY                42
BOOKS_AND_REFERENCE  169
BUSINESS             262

In [133]:
# Count the number of Installs by category (Category Concentration)
category_installs = df_apps_clean.groupby('Category').agg({'Installs':pd.Series.sum})
category_installs.head()

                       Installs
Category
ART_AND_DESIGN        114233100
AUTO_AND_VEHICLES      53129800
BEAUTY                 26916200
BOOKS_AND_REFERENCE  1665791655
BUSINESS              692018120

In [134]:
# Merge and combine the two dataframes
cat_merged_df = pd.merge(cat_number, category_installs, on='Category', how='inner')
print(f'The dimensions of the Dataframe are: {cat_merged_df.shape}')

The dimensions of the Dataframe are: (33, 2)

In [135]:
# Sort by number of Installs
cat_merged_df.sort_values('Installs', ascending=False).head()

               App     Installs
Category
GAME           910  13858762717
COMMUNICATION  257  11039241530
TOOLS          719   8099724500
PRODUCTIVITY   301   5788070180
SOCIAL         203   5487841475

In [136]:
scatter = px.scatter(cat_merged_df,
                     x='App',
                     y='Installs',
                     title='Category Concentration',
                     size='App',
                     hover_name=cat_merged_df.index,
                     color='Installs')

scatter.update_layout(xaxis_title="Number of Apps (Lower=More Concentrated)",
                      yaxis_title="Installs",
                      yaxis=dict(type='log'))
scatter.show()

# Extracting Nested Data from a Column

**Challenge**: How many different types of genres are there? Can an app belong to more than one genre? Check what happens when you use .value_counts() on a column with nested values? See if you can work around this problem by using the .split() function and the DataFrame's [.stack() method](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.stack.html).

In [137]:
# Get number of different Genres
len(df_apps_clean.Genres.unique())

114

In [138]:
# Display and count the different Genres
df_apps_clean.Genres.value_counts().sort_values(ascending=True)[:5]

Genres
Adventure;Education            1
Lifestyle;Pretend Play         1
Strategy;Education             1
Communication;Creativity       1
Music & Audio;Music & Video    1
Name: count, dtype: int64

In [139]:
# Split the strings on the semi-colon and then .stack them.
stack = df_apps_clean.Genres.str.split(';', expand=True).stack()
print(f'We now have a single column with shape: {stack.shape}')
num_genres = stack.value_counts()
print(f'Number of genres: {len(num_genres)}')

We now have a single column with shape: (8564,)
Number of genres: 53

In [140]:

num_genres.head()

Tools            719
Education        587
Entertainment    498
Action           304
Productivity     301
Name: count, dtype: int64

# Colour Scales in Plotly Charts - Competition in Genres

**Challenge**: Can you create this chart with the Series containing the genre data?

<img src=https://imgur.com/DbcoQli.png width=400>

Try experimenting with the built in colour scales in Plotly. You can find a full list [here](https://plotly.com/python/builtin-colorscales/).

* Find a way to set the colour scale using the color_continuous_scale parameter.
* Find a way to make the color axis disappear by using coloraxis_showscale.

In [141]:
# Plot the Genre data
# colorscales = px.colors.named_colorscales()

bar = px.bar(x = num_genres.index[:15],
             y = num_genres.values[:15],
             title='Top Genres',
             hover_name=num_genres.index[:15],
             color=num_genres.values[:15],
             color_continuous_scale='Agsunset'
             )

bar.update_layout(xaxis_title='Genre',
                  yaxis_title='Number of Apps',
                  coloraxis_showscale=True)


bar.show()

# Grouped Bar Charts: Free vs. Paid Apps per Category

In [142]:
# Group App by 'Category' then by 'Type'
df_free_vs_paid = df_apps_clean.groupby(['Category', 'Type',],
                                        as_index=False).agg({'App': pd.Series.count})


df_free_vs_paid.head()

            Category  Type  App
0     ART_AND_DESIGN  Free   58
1     ART_AND_DESIGN  Paid    3
2  AUTO_AND_VEHICLES  Free   72
3  AUTO_AND_VEHICLES  Paid    1
4             BEAUTY  Free   42

**Challenge**: Use the plotly express bar [chart examples](https://plotly.com/python/bar-charts/#bar-chart-with-sorted-or-ordered-categories) and the [.bar() API reference](https://plotly.com/python-api-reference/generated/plotly.express.bar.html#plotly.express.bar) to create this bar chart:

<img src=https://imgur.com/LE0XCxA.png>

You'll want to use the `df_free_vs_paid` DataFrame that you created above that has the total number of free and paid apps per category.

See if you can figure out how to get the look above by changing the `categoryorder` to 'total descending' as outlined in the documentation here [here](https://plotly.com/python/categorical-axes/#automatically-sorting-categories-by-name-or-total-value).

In [143]:
g_bar = px.bar(df_free_vs_paid,
               x='Category',
               y='App',
               title='Free vs. Paid Apps per Category',
               color='Type',
               barmode='group'
               )

g_bar.update_layout(xaxis_title='Category',
                    yaxis_title='Number of Apps',
                    xaxis={'categoryorder':'total descending', 'tickangle': 90},
                    yaxis=dict(type='log')
                    )

g_bar.show()

# Plotly Box Plots: Lost Downloads for Paid Apps

**Challenge**: Create a box plot that shows the number of Installs for free versus paid apps. How does the median number of installations compare? Is the difference large or small?

Use the [Box Plots Guide](https://plotly.com/python/box-plots/) and the [.box API reference](https://plotly.com/python-api-reference/generated/plotly.express.box.html) to create the following chart.

<img src=https://imgur.com/uVsECT3.png>

In [144]:
box = px.box(df_apps_clean,
             y='Installs',
             x='Type',
             color='Type',
             notched=True,
             points='all',
             title='How Many Downloads are Paid Apps Giving Up?'
             )

box.update_layout(yaxis=dict(type='log'))

box.show()

# Plotly Box Plots: Revenue by App Category

**Challenge**: See if you can generate the chart below:

<img src=https://imgur.com/v4CiNqX.png>

Looking at the hover text, how much does the median app earn in the Tools category? If developing an Android app costs $30,000 or thereabouts, does the average photography app recoup its development costs?

Hint: I've used 'min ascending' to sort the categories.

In [145]:
df_apps_clean.head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Revenue Estimate
21,KBA-EZ Health Guide,MEDICAL,5.00,4,25.00,1,Free,0.00,Everyone,Medical,0.00
28,Ra Ga Ba,GAME,5.00,2,20.00,1,Paid,1.49,Everyone,Arcade,1.49
47,Mu.F.O.,GAME,5.00,2,16.00,1,Paid,0.99,Everyone,Arcade,0.99
82,Brick Breaker BR,GAME,5.00,7,19.00,5,Free,0.00,Everyone,Arcade,0.00
99,Anatomy & Physiology Vocabulary Exam Review App,MEDICAL,5.00,1,4.60,5,Free,0.00,Everyone,Medical,0.00

In [146]:
df_paid_apps = df_apps_clean[df_apps_clean.Type == 'Paid']

box = px.box(df_paid_apps,
             x='Category',
             y='Revenue Estimate',
             title='How Much Can Paid Apps Earn'
             )

box.update_layout(yaxis=dict(type='log'),
                  xaxis_title='Category',
                  yaxis_title='Paid app Ballpark Revenue',
                  xaxis_tickangle=30,
                  xaxis={'categoryorder':'min ascending'}
                  )


box.show()

# How Much Can You Charge? Examine Paid App Pricing Strategies by Category

**Challenge**: What is the median price price for a paid app? Then compare pricing by category by creating another box plot. But this time examine the prices (instead of the revenue estimates) of the paid apps. I recommend using `{categoryorder':'max descending'}` to sort the categories.

In [147]:
box = px.box(df_paid_apps,
             x='Category',
             y="Price",
             title='Price per Category')

box.update_layout(xaxis_title='Category',
                  yaxis_title='Paid App Price',
                  xaxis={'categoryorder':'max descending'},
                  yaxis=dict(type='log'))

box.show()